import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 250, lines = 75 }
dynamic_title = true
padding = { x = 10, y = 25 }
dynamic_padding = true
decorations = "transparent"
opacity = 0.9
blur = true
option_as_alt = "Both"

[scrolling]
history = 10000

[font]
normal = { family = "RobotoMono Nerd Font" }
size = 13
